apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  serviceName: "kafka"
  replicas: 2
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: kafka-base:local-v1
        command: ["/bin/bash", "start-kafka.sh"]
        ports:
        - name: listener
          containerPort: 9092
        - name: jmxexporter
          containerPort: 7171
