apiVersion: v1
kind: Service
metadata:
  name: mirrormaker
  labels:
    app: mirrormaker
spec:
  clusterIP: None
  selector:
    app: mirrormaker
  ports:
  - name: zookeeper
    port: 2181
  - name: kafka
    port: 9092
