apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
    jmxexporter: enabled
spec:
  clusterIP: None
  selector:
    app: zookeeper
  ports:
  - name: listener
    port: 2181
  - name: zookeeper-2888
    port: 2888
  - name: zookeeper-3888
    port: 3888
  - name: jmxexporter
    port: 7171
